### PR TITLE
Reduce memory allocation

### PR DESCRIPTION
**Pull request by gssbzn**
Removing addressable reduce a lot the number of object allocated
Taking a more similar approach to Rails `current_page?` method to calculate current path

Some stats from our app with about 5 links using the helper
**Before**
Memory(bytes): **23871**
Objects: **226**
**After**
Memory(bytes): **7960**
Objects: **136**

Some other minor changes to try to improve gem settings

### CODE REVIEW

**Comment by GBH** [comment]
I don't even recall why `addressable` was introduced in the first place. Wonder if removing it will introduce unexpected regressions (that are clearly not tested). I'm thinking about releasing 2.0 eventually that will tweak API a bit as I don't like how params are handled. So I'll merge this PR then.

**Comment by gssbzn** [comment]
@GBH there' some small difference on matching paths without addressable, Rails approach is more naive but at least the test suite are passing and I've been using my branch without any major problem

**Comment by ali-ehmed** [comment]
Cool @gssbzn

**Comment by saiqulhaq** [comment]
@gssbzn are you using your branch on your production app? it would be great if this PR is not caused any regression

**Comment by gssbzn** [comment]
@saiqulhaq We've been using it without any kind of problem so far

**Comment by gssbzn** [comment]
I'm closing this as I'm no longer actively working with Ruby

**Pull request closed without merging**
